version: '3.9'

volumes:
    ftp:

services:
  # ssh:
  #   build: ssh
  #   restart: always
  #   ports:
  #     - 22:22
  #   volumes:
  #     - ./ssh/conf/sshd_config:/etc/ssh/sshd_config:ro
  #     - ./ssh/services.d:/etc/services.d:ro

  flask:
    build: flask
    ports:
      - "5000:5000"
    expose:
      - 5000

      
  ftpd:
    build: ftp
    ports:
        - "20-21:20-21"
        - "65500-65515:65500-65515"
  
    volumes: 
      - ftp:/var/ftp